# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f1d18b34ccc0cab96d2e60edc86e0daab5b06fd51fd97cd870b4600af4a83415962e46739689f4d4b96197f51cd05675fe0f9cd5d884ec28e4ecc636bea04979

test:
  secret_key_base: b359ed75495af581a0bb4e98bb12ac2f99fb63ddcd48ff6e1244de9b3951b6c6946a097540dd10d3f5fbe7d321c4c80d9acc79b3722a86b72a45a9d3fceb7441

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
